# .github/workflows/test.yml
name: Local Manual Use ArgoCD CLI Action

# Додаємо подію для ручного запуску
on: 
  workflow_dispatch:

jobs:
  local-use-argocd-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install and run ArgoCD CLI with app sync
      #   uses: ./ # Local execution with act
      #   with:
      #     server: ${{ secrets.GHA_ARGO_CD_CLI_SERVER }}
      #     token: ${{ secrets.GHA_ARGO_CD_CLI_TOKEN }}
      #     app: ${{ vars.GHA_ARGO_CD_CLI_APP }}
      #     command: 'app sync'
      #     args: '--prune'

      - name: Check ArgoCD application status
        # ./ - Local execution with act
        # AGvin/gha-argo-cd-cli@v0.0.0 - default execution
        uses: ./
        with:
          server: ${{ secrets.GHA_ARGO_CD_CLI_SERVER }}
          token: ${{ secrets.GHA_ARGO_CD_CLI_TOKEN }}
          app: ${{ vars.GHA_ARGO_CD_CLI_APP }}
          command: 'app get'
